local T = require("test.ljs_test")
local parser = require("ljs.parser")
local test, assert_eq = T.test, T.assert_eq

local function assert_empty(stmt)
  assert_eq(stmt.type, "EmptyStatement", "expected EmptyStatement")
end

test("bare semicolon", function()
  local ast, err = parser.parse(";")
  assert(ast ~= nil, "expected ast")
  assert_eq(ast.type, "Program")
  assert_eq(#ast.body, 1)
  assert_empty(ast.body[1])
end)

test("multiple semicolons", function()
  local ast, err = parser.parse(";;;")
  assert(ast ~= nil)
  assert_eq(#ast.body, 3)
  assert_empty(ast.body[1])
  assert_empty(ast.body[2])
  assert_empty(ast.body[3])
end)

test("semicolon inside block", function()
  local ast, err = parser.parse("{;}")
  assert(ast ~= nil)
  assert_eq(#ast.body, 1)
  assert_eq(ast.body[1].type, "BlockStatement")
  assert_eq(#ast.body[1].body, 1)
  assert_empty(ast.body[1].body[1])
end)

test("semicolon after function declaration", function()
  local ast, err = parser.parse("function f() {};")
  assert(ast ~= nil)
  assert_eq(#ast.body, 2)
  assert_eq(ast.body[1].type, "FunctionDeclaration")
  assert_empty(ast.body[2])
end)

test("semicolons between expression statements", function()
  local ast, err = parser.parse("1; ; 2;")
  assert(ast ~= nil)
  assert_eq(#ast.body, 3)
  assert_eq(ast.body[1].type, "ExpressionStatement")
  assert_empty(ast.body[2])
  assert_eq(ast.body[3].type, "ExpressionStatement")
end)

test("function add example from README/issue #203", function()
  local ljs = require("ljs")
  local fn, err = ljs.load("function add(a,b) { return a + b; }; add")
  assert_eq(err, nil)
  assert(fn ~= nil, "expected function")
  local add = fn()
  assert(add ~= nil, "expected inner function")
  assert_eq(add(3, 4), 7)
end)
