// Flexoki — an inky color scheme for prose and code
// Copyright (c) 2023 Steph Ango — MIT License
// https://github.com/kepano/flexoki

import { createTheme } from "@uiw/codemirror-themes";
import { tags as t } from "@lezer/highlight";

export const flexokiDark = createTheme({
  theme: "dark",
  settings: {
    background: "#100F0F",
    foreground: "#CECDC3",
    caret: "#CECDC3",
    selection: "#CECDC333",
    selectionMatch: "#CECDC333",
    lineHighlight: "#1C1B1A",
    gutterBackground: "#100F0F",
    gutterForeground: "#403E3C",
    gutterBorder: "#343331",
  },
  styles: [
    { tag: t.comment, color: "#6F6E69" },
    { tag: t.lineComment, color: "#6F6E69" },
    { tag: t.blockComment, color: "#6F6E69" },
    { tag: t.docComment, color: "#6F6E69" },
    { tag: t.name, color: "#CECDC3" },
    { tag: t.variableName, color: "#CECDC3" },
    { tag: t.definition(t.variableName), color: "#CECDC3" },
    { tag: t.local(t.variableName), color: "#CECDC3" },
    { tag: t.special(t.variableName), color: "#D14D41" },
    { tag: t.function(t.variableName), color: "#4385BE" },
    { tag: t.definition(t.function(t.variableName)), color: "#4385BE" },
    { tag: t.keyword, color: "#D14D41" },
    { tag: t.controlKeyword, color: "#D14D41" },
    { tag: t.operatorKeyword, color: "#D14D41" },
    { tag: t.moduleKeyword, color: "#D14D41" },
    { tag: t.string, color: "#879A39" },
    { tag: t.special(t.string), color: "#879A39" },
    { tag: t.regexp, color: "#DA702C" },
    { tag: t.escape, color: "#DA702C" },
    { tag: t.number, color: "#DA702C" },
    { tag: t.integer, color: "#DA702C" },
    { tag: t.float, color: "#DA702C" },
    { tag: t.bool, color: "#D14D41" },
    { tag: t.null, color: "#D14D41" },
    { tag: t.operator, color: "#CECDC3" },
    { tag: t.typeName, color: "#D0A215" },
    { tag: t.definition(t.typeName), color: "#D0A215" },
    { tag: t.className, color: "#D0A215" },
    { tag: t.labelName, color: "#D0A215" },
    { tag: t.propertyName, color: "#CECDC3" },
    { tag: t.definition(t.propertyName), color: "#CECDC3" },
    { tag: t.tagName, color: "#D14D41" },
    { tag: t.attributeName, color: "#D0A215" },
    { tag: t.attributeValue, color: "#879A39" },
    { tag: t.punctuation, color: "#6F6E69" },
    { tag: t.separator, color: "#6F6E69" },
    { tag: t.bracket, color: "#6F6E69" },
    { tag: t.angleBracket, color: "#6F6E69" },
    { tag: t.special(t.brace), color: "#6F6E69" },
    { tag: t.meta, color: "#6F6E69" },
    { tag: t.comment, color: "#6F6E69", fontStyle: "italic" },
    { tag: t.docComment, color: "#6F6E69", fontStyle: "italic" },
    { tag: t.processingInstruction, color: "#6F6E69" },
    { tag: t.inserted, color: "#879A39" },
    { tag: t.deleted, color: "#D14D41" },
    { tag: t.changed, color: "#D0A215" },
    { tag: t.link, color: "#4385BE" },
    { tag: t.heading, color: "#D14D41", fontWeight: "bold" },
    { tag: t.strong, fontWeight: "bold" },
    { tag: t.emphasis, fontStyle: "italic" },
    { tag: t.strikethrough, textDecoration: "line-through" },
  ],
});
